### ISSUE TITLE
[CI] unit-test-cpu fails on every PR since 2026-09-07: test_spec_accept_metrics.py hits `Scheduler has no attribute server_args` (#1555 x #1586)

### ISSUE THREAD

**Issue by zorrofox** [sgl-project/sglang-jax#1608]
## Symptom

The `unit-test-cpu` job of `PR Test` has failed on every run since 2026-09-07 ~14:00 UTC, e.g. #1547 (`045ff682`), #1549 (`df52b39c`), #1606 (`ccb2d663`, `5389c4fd`), #1607 (`43fda8e3`). Same failure each time:

```
python/sgl_jax/test/test_spec_accept_metrics.py
  File "python/sgl_jax/srt/managers/scheduler_metrics_mixin.py", line 122, in init_metrics
    self.queue_time = create_queue_time_histogram() if self.server_args.enable_metrics else None
AttributeError: 'Scheduler' object has no attribute 'server_args'
FAILED (errors=5)
AssertionError: expected return code 0, but python/sgl_jax/test/test_spec_accept_metrics.py returned 1
```

## Cause

Two PRs merged the same day were each green on their own and conflict semantically:

- #1555 (`d02e8b55`, merged 2026-09-07 11:37 UTC) made `SchedulerMetricsMixin.init_metrics` read `self.server_args.enable_metrics` for the queue-time histogram (`scheduler_metrics_mixin.py:122`).
- #1586 (`50d59b48`, merged 2026-09-07 14:07 UTC; its last commit and CI run are from 01:28 UTC, before #1555 landed) added `python/sgl_jax/test/test_spec_accept_metrics.py`, which builds schedulers with `Scheduler.__new__(Scheduler)` / `types.SimpleNamespace()` and calls `SchedulerMetricsMixin.init_metrics` before any `server_args` is assigned (four call sites: lines 76-77, 82-83, 115-116, 150-151; the third one assigns `server_args` only after `init_metrics`).

Reproduces locally on CPU with jax 0.11.1 / Python 3.12: `python -m pytest python/sgl_jax/test/test_spec_accept_metrics.py` gives 5 failed / 3 passed with the same five `AttributeError`s.

## Suggested fix

Test-side: give each bare object a minimal `server_args` before `init_metrics`, e.g. `types.SimpleNamespace(enable_metrics=False)` (and fold the existing `decode_log_interval=1` namespace into it). Verified locally: the file goes to 8 passed. Alternatively `init_metrics` could tolerate a missing `server_args` with `getattr`, but the test-side change keeps the mixin contract explicit.

Since this blocks the `e2e-test-1-tpu` job (`needs: [unit-test-1-tpu, unit-test-cpu]`) for every open PR, flagging it here rather than piling another PR on top.

**Comment by JamesBrianD** [comment]
I will fix this bugs as soon as possible.
