### ISSUE TITLE
[Bug] Three test files fail on every PR since #1574 (JAX bump + Flax unpin)

### ISSUE THREAD

**Issue by real3stone** [sgl-project/sglang-jax#1597]
## Summary

#1574 (`[chore] bump JAX version and unpin Flax`, merged 2026-09-03) changed two things:

```diff
-    "flax==0.12.4",            +    "flax",
-    "jax[tpu]==0.10.2",        +    "jax[tpu]==0.11.1",
```

Each half broke a different test. Any PR that reaches the 4-chip suites now fails:

| Failing file | Suite | Cause |
| --- | --- | --- |
| `test/srt/multimodal/test_wan2_1_models.py` | `e2e-test-tpu-v6e-4` | Flax unpin → 0.12.9 |
| `test/srt/test_speculative_decoding.py` | `accuracy-test-tpu-v6e-4` | JAX 0.11.1 sharding |
| `python/sgl_jax/test/layers/test_lightning_backend.py` | `unit-test-tpu-v6e-4` | JAX 0.11.1 sharding |

Both causes reproduce on CPU — no TPU needed to confirm either.

## 1. Flax unpin — `NDRotaryEmbedding`

`python/pyproject.toml:15` is now a bare `"flax"`, which resolves to 0.12.9. Flax 0.12 rejects
data held in a static Pytree attribute, and `rotary_embedding.py:82` assigns a plain list:

```python
self.rope_generators = []
```

The server dies during model construction, before any device work:

```
ValueError: Found unexpected data on value of type <class 'list'> in static attribute
'rope_generators' of Pytree type '...multimodal.layers.rotary_embedding.NDRotaryEmbedding'.
```

Repro:

```python
from flax import nnx
from sgl_jax.srt.multimodal.layers.rotary_embedding import NDRotaryEmbedding
nnx.eval_shape(lambda: NDRotaryEmbedding(rope_dim_list=[16, 16, 16], rope_theta=10000.0))
```

**The unpin was required — pinning flax back is not an option.** Flax's declared `jax>=0.8.1` is
inaccurate. Measured against `jax==0.11.1` (CPU, one venv per version):

| flax | result with jax 0.11.1 |
| --- | --- |
| 0.12.4 / 0.12.5 / 0.12.6 | fails to import: `AttributeError: jax.core.Effect was deprecated in JAX v0.10.0 and removed in JAX v0.11.0` (`flax/nnx/variablelib.py:324`) |
| 0.12.7 / 0.12.8 | fails to import: `AttributeError: module 'jax.experimental.hijax' has no attribute 'MutableHiType'` |
| **0.12.9** | imports fine; only `NDRotaryEmbedding` construction fails, as above |

0.12.9 is the only flax that works with jax 0.11.1, so #1574 unpinning it was correct and the fix
has to be in this repo. Flax's error suggests two in-code remedies — `nnx.data(...)` around the
list, or `pytree=False` on the class; I have not checked which one preserves the intended
semantics here, so I would rather the multimodal owner picks.

> *Edited 2026-09-06: an earlier revision of this issue claimed the unpin was unnecessary and that
> restoring an upper bound would fix this. That was wrong — it was inferred from flax's declared
> metadata rather than measured. The table above is the measured result.*

## 2. JAX 0.11.1 — mismatched shardings are now an error

0.11.1 rejects operands whose shardings differ where 0.10.2 accepted them. Two sites:

### `draft_extend_fused.py:641` — `_per_dp_cumsum_device`

```
ShardingTypeError: All operands should have the same sharding.
Got ... spec=P(None, None) ... spec=P('data', None)
```

The slice is what drops the sharding — `zeros` only inherits it:

```
lens_2d           P('data', None)
lens_2d[:, :1]    P(None, None)     <-- here
zeros_like(...)   P(None, None)
cumsum(lens_2d)   P('data', None)
```

Repro on 4 CPU devices:

```bash
JAX_PLATFORMS=cpu XLA_FLAGS=--xla_force_host_platform_device_count=4 python - <<'PY'
import jax, jax.numpy as jnp
from jax.sharding import NamedSharding, PartitionSpec as P, AxisType
from sgl_jax.srt.speculative.draft_extend_fused import _per_dp_cumsum_device

mesh = jax.make_mesh((1, 4), ("data", "tensor"),
                     axis_types=(AxisType.Explicit, AxisType.Explicit))
with jax.sharding.set_mesh(mesh):
    lens = jax.device_put(jnp.arange(1, 9, dtype=jnp.int32), NamedSharding(mesh, P(None)))
    jax.jit(lambda x: _per_dp_cumsum_device(x, 1))(lens)
PY
```

Fix (verified for `dp_size` 1 and 2):

```python
zeros = jnp.zeros_like(lens_2d[:, :1], dtype=jnp.int32)
row_sharding = jax.typeof(lens_2d).sharding
if isinstance(row_sharding, NamedSharding) and not row_sharding.mesh.empty:
    zeros = jax.sharding.reshard(zeros, row_sharding)
```

### `simple_gla/native.py:49` — `naive_gla_decode`

```python
o = jnp.einsum("bhk,bhkv->bhv", q_t, h1)
```

```
ShardingTypeError: dot_general requires lhs batch dimensions and rhs batch dimensions
to have the same sharding, got (None, None) and ('data', 'tensor').
```

3 of 22 tests in `test_lightning_backend.py` fail here. I have not worked out a fix for this one.

## These three are a lower bound

`run_suite.py` aborts at the first failing file in a partition, so each red job hides whatever
would have run after it. Expect more failures to surface once these are fixed.

## Environment

CI installs `flax==0.12.9`, `jax==0.11.1`, `jaxlib==0.11.1`, `libtpu==0.0.46.1`.
File and line references are against `main` at the time of filing.

**Comment by real3stone** [comment]
This part has already been fixed.
